version: "3.3"

services:
  sin-db:
    build:
      context: docker
      dockerfile: Dockerfile.postgresql
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  sin-wildfly:
    build:
      context: docker
      dockerfile: Dockerfile.wildfly
    links:
      - sin-db
    ports:
      - 8080:8080
      - 9990:9990
