spring:
  jmx:
    default-domain: sin
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    rest:
      base-path: "/api"
  datasource:
    jndi-name: java:jboss/datasources/SIN-project-example
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          auto: create-drop

server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/css,application/javascript
  port: 8081
